local path = "plugins/configs/"

require(path .. "colorizer")
require(path .. "lualine")
require(path .. "material")
require(path .. "treesitter")
require(path .. "telescope")
require(path .. "nvim-tree")
require(path .. "virt-column")
require(path .. "indent_blankline")
require(path .. "barbar")
require(path .. "noice")
require(path .. "vim-visual-multi")
require(path .. "gitgutter")
require(path .. "coc")
