return {
  meta = {
    name = "dark",
    style = "modern"
  },

  -- Common colors
  white =    '#CCCCCC',
  gray =     '#717CB4',
  black =    '#000000',
  red =      '#FE5E78',
  green =    '#4EC9B0',
  yellow =   '#DCDCAA',
  blue =     '#569CD6',
  paleblue = '#9CDCFE',
  cyan =     '#4FC1FF',
  purple =   '#C586C0',
  orange =   '#CE9178',
  pink =     '#DA70D6',

  -- Dark colors
  darkred =    '#AC455F',
  darkgreen =  '#4EC9B0',
  darkyellow = '#DCDCAA',
  darkblue =   '#569CD6',
  darkcyan =   '#4FC1FF',
  darkpurple = '#C586C0',
  darkorange = '#CE9178',

  error =  '#FE5E78',
  link =   '#80CBC4',
  cursor = '#AEAFAD',
  title =  '#EEFFFF',

  none =         'NONE',
  bg =           '#1F1F1F',
  bg_alt =       '#181818',
  fg =           '#CCCCCC',
  text =         '#717CB4',
  comments =     '#6A9955',
  selection =    '#484848',
  contrast =     '#181818',
  active =       '#404040',
  virt_column =  '#404040',
  border =       '#404040',
  line_numbers = '#6E7681',
  highlight =    '#303030',
  disabled =     '#464B5D',
  accent =       '#0078D4',
  visual =       '#264F78',
  ["@number"] = '#B5CEA8',
  ["@string"] = '#CE9178',
  ["@boolean"] = '#B5CEA8',
  ["@constant.builtin"] = '#B5CEA8',
  ["@variable"] =     '#4FC1FF',
  ["@punctuation"] =  '#CCCCCC',
  ["@punctuation.delimiter"] =  '#CCCCCC',
  ["@function"] = '#DCDCAA',
  ["@attribute"] = '#DCDCAA',
  ["@parameter"] = '#9CDCFE',
  ["@property"] =     '#9CDCFE',
  ["@operator"] =     '#CCCCCC',
  ["@keyword"] = '#569CD6',
  ["@keyword.operator"] = '#569CD6',
  ["@tag"] = '#569CD6',
  ["@tag.delimiter"] = '#CCCCCC',
  ["@type"] = '#4EC9B0',
  ["@type.builtin"] = '#4EC9B0',
  -- ["@type.qualifier"] = '#569CD6',
  -- ["@constructor"] = '#4EC9B0',
  folder =       '#DDDDDD',

  floating_window              = '#2A2A2A',
  floating_window_current_line = '#04395E',

  git = {
    added = '#6A9955',
    modified = '#569CD6',
    removed = '#DC6068'
  },
}
